# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stackinator < Formula
  desc "Minimal CLI tool for managing stacked branches and syncing them to GitHub Pull Requests"
  homepage "https://github.com/javoire/stackinator"
  version "1.8.0"
  license "MIT"

  depends_on "gh"
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/javoire/stackinator/releases/download/v1.8.0/stackinator_Darwin_x86_64.tar.gz"
      sha256 "785c3913b4ac77dc775a281a3260896c4b93ac948c31415c03414c439928b22b"

      def install
        bin.install "stack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/javoire/stackinator/releases/download/v1.8.0/stackinator_Darwin_arm64.tar.gz"
      sha256 "6b717b3f137a9da534b57f5121c49a3a3b68552e017c622c601471697c130c1e"

      def install
        bin.install "stack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/javoire/stackinator/releases/download/v1.8.0/stackinator_Linux_x86_64.tar.gz"
      sha256 "0b3e1c9806602ffd396b84436785059d096e03d2dc1e05abe84bd1104d46490a"
      def install
        bin.install "stack"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/javoire/stackinator/releases/download/v1.8.0/stackinator_Linux_arm64.tar.gz"
      sha256 "30e049c986b04af3ca912e86279b84d0c6057591269b173d6977f15cbead119d"
      def install
        bin.install "stack"
      end
    end
  end

  def caveats
    <<~EOS
      Get started:

        stack new <branch-name>
        stack status
        stack sync
        stack --help
    EOS
  end

  test do
    system "#{bin}/stack", "--version"
  end
end
