# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stackinator < Formula
  desc "Minimal CLI tool for managing stacked branches and syncing them to GitHub Pull Requests"
  homepage "https://github.com/javoire/stackinator"
  version "1.0.2"
  license "MIT"

  depends_on "gh"
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/javoire/stackinator/releases/download/v1.0.2/stackinator_Darwin_x86_64.tar.gz"
      sha256 "d53a2c1b7102ea74a9110a59576880c70044f467abed2deb01762b97ed40d2dc"

      def install
        bin.install "stack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/javoire/stackinator/releases/download/v1.0.2/stackinator_Darwin_arm64.tar.gz"
      sha256 "436e859ec6b74571014790d08d41c4a5eb87ce7a49e336c2dc20948c49125c91"

      def install
        bin.install "stack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/javoire/stackinator/releases/download/v1.0.2/stackinator_Linux_x86_64.tar.gz"
      sha256 "619b8e22064569a97cfb822fea006914a51785036de32ecf572d6e0100d6f62f"
      def install
        bin.install "stack"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/javoire/stackinator/releases/download/v1.0.2/stackinator_Linux_arm64.tar.gz"
      sha256 "3f7889404df8a0631f097bd0c0f952c91f946e1d511324361dc72c7d3500ebf7"
      def install
        bin.install "stack"
      end
    end
  end

  test do
    system "#{bin}/stack", "--version"
  end
end
