# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stack < Formula
  desc "Minimal CLI tool for managing stacked branches and syncing them to GitHub Pull Requests"
  homepage "https://github.com/javoire/stackinator"
  version "1.0.1"
  license "MIT"

  depends_on "gh"
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/javoire/stackinator/releases/download/v1.0.1/stackinator_Darwin_x86_64.tar.gz"
      sha256 "64087d2d5a212b39e99f64f848867dd0cca1e1c6d4f2380667d9eff7f5fd2836"

      def install
        bin.install "stack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/javoire/stackinator/releases/download/v1.0.1/stackinator_Darwin_arm64.tar.gz"
      sha256 "2ed18e046fb077e97a55fa00dbd4e981392e836466e2a692b440aab1300a961a"

      def install
        bin.install "stack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/javoire/stackinator/releases/download/v1.0.1/stackinator_Linux_x86_64.tar.gz"
      sha256 "1a78cfe62372d3fed368ab0d0e9b67c75886bb1b586fd78c00773d833bf1a8ac"
      def install
        bin.install "stack"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/javoire/stackinator/releases/download/v1.0.1/stackinator_Linux_arm64.tar.gz"
      sha256 "72f91ec1ca546d5ea2658259fbb6be346427d29781b3859c03f33c1a27c557d4"
      def install
        bin.install "stack"
      end
    end
  end

  test do
    system "#{bin}/stack", "--version"
  end
end
